/**
 * Created by sabir on 26.08.15.
 */
var constants = {
    PARSE_APP_ID: 'h1QhtsSjeoyQSa8RDQBDPvgbnI7Ix6nadHTsepwN',
    PARSE_JS_KEY: 'Ci34OXCgbv7TuVOiUJFOmoSwULbC7JRnxvFaT1ZI',
    PARSE_REST_API_KEY: '',

    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',


    //ADMIN
    ADMIN_AUDITOR_EXERCISE_CLICKED: 'ADMIN_AUDITOR_EXERCISE_CLICKED',
    ADMIN_LOAD_ALL_AUDITOR_EXERCISES: 'ADMIN_LOAD_ALL_AUDITOR_EXERCISES'

}

module.exports = constants;