/**
 * Created by sabir on 10.09.15.
 */

var constants = {
    NOTE_LOADED: 'NOTE_LOADED',
    NOTE_UPDATED: 'NOTE_UPDATED',
    TEACHER_NOTES_LOADED: 'TEACHER_NOTES_LOADED',
    NOTE_CREATED: 'NOTE_CREATED',

    ATTACHMENT_CREATED: 'ATTACHMENT_CREATED',
    ATTACHMENT_DELETED: 'ATTACHMENT_DELETED',
    ATTACHMENTS_LOADED: 'ATTACHMENTS_LOADED'
}

module.exports = constants;